import type { AppState } from '../types';

export const DEMO_PRESET: AppState = {
  croppedImageSrc: '/og-image.png',
  title: 'Nier Automata - 2B',
  creator: '@reconeur',
  items: {
    mainhand: {
      id: 'mainhand',
      label: '',
      name: '유령선 검',
      nameKo: '유령선 검',
      nameEn: 'Ghost Barque Katana',
      nameJa: 'ゴーストバーク・ブレード',
      iconPath: '/i/036000/036451.png',
      dye1: 'Soot Black',
    },
    offhand: { id: 'offhand', label: '', name: '' },
    head: {
      id: 'head',
      label: '',
      name: '2호 B형 고글',
      nameKo: '2호 B형 고글',
      nameEn: 'No.2 Type B Goggles',
      nameJa: '二号B型ゴーグル',
      iconPath: '/i/040000/040845.png',
    },
    body: {
      id: 'body',
      label: '',
      name: '2호 B형 전투복',
      nameKo: '2호 B형 전투복',
      nameEn: 'No.2 Type B Dress',
      nameJa: '二号B型戦闘服',
      iconPath: '/i/042000/042682.png',
    },
    hands: {
      id: 'hands',
      label: '',
      name: '2호 B형 장갑',
      nameKo: '2호 B형 장갑',
      nameEn: 'No.2 Type B Gloves',
      nameJa: '二号B型グローブ',
      iconPath: '/i/044000/044766.png',
    },
    legs: {
      id: 'legs',
      label: '',
      name: '2호 B형 쫄바지',
      nameKo: '2호 B형 쫄바지',
      nameEn: 'No.2 Type B Leggings',
      nameJa: '二号B型タイツ',
      iconPath: '/i/047000/047668.png',
    },
    feet: {
      id: 'feet',
      label: '',
      name: '2호 B형 장화',
      nameKo: '2호 B형 장화',
      nameEn: 'No.2 Type B Boots',
      nameJa: '二号B型ブーツ',
      iconPath: '/i/049000/049207.png',
    },
    ears: { id: 'ears', label: '', name: '' },
    neck: { id: 'neck', label: '', name: '' },
    wrists: { id: 'wrists', label: '', name: '' },
    rings: { id: 'rings', label: '', name: '' },
    rings2: { id: 'rings2', label: '', name: '' },
    face: { id: 'face', label: '', name: '' },
  },
};
