import type { FF14Dye } from '../types';

export const FF14_DYES: FF14Dye[] = [
    // ── 기본색 (드롭다운 최상단 고정) ─────────────────────────────────────────
    { name: '기본색', nameEn: 'None', nameJa: 'なし', hex: 'transparent' },

    // ── 회색 / 흑백 계열 ──────────────────────────────────────────────────────
    { name: '하얀눈색', nameEn: 'Snow White', nameJa: 'スノウホワイト', hex: '#E4DFD1' },
    { name: '회색', nameEn: 'Ash Grey', nameJa: 'アッシュグレイ', hex: '#777677' },
    { name: '구부 회색', nameEn: 'Goobbue Grey', nameJa: 'グゥーブーグレイ', hex: '#878174' },
    { name: '진회색', nameEn: 'Slate Grey', nameJa: 'スレートグレイ', hex: '#5E5E5E' },
    { name: '탄회색', nameEn: 'Charcoal Grey', nameJa: 'チャコール그레이', hex: '#3B3938' },
    { name: '숯검정색', nameEn: 'Soot Black', nameJa: 'スートブラック', hex: '#1D1D1D' },

    // ── 분홍 / 빨강 계열 ──────────────────────────────────────────────────────
    { name: '장미색', nameEn: 'Rose Pink', nameJa: 'ローズピンク', hex: '#E4B5B5' },
    { name: '라일락색', nameEn: 'Lilac Purple', nameJa: 'ライラックパープル', hex: '#816781' },
    { name: '롤란베리색', nameEn: 'Rolanberry Red', nameJa: 'ロランベリーレッド', hex: '#511317' },
    { name: '달라가브색', nameEn: 'Dalamud Red', nameJa: 'ダラガブレッド', hex: '#7E0B0B' },
    { name: '녹슨 빨간색', nameEn: 'Rust Red', nameJa: 'ラストレッド', hex: '#4F1212' },
    { name: '포도주색', nameEn: 'Wine Red', nameJa: 'ワインレッド', hex: '#310D12' },
    { name: '산호색', nameEn: 'Coral Pink', nameJa: 'コーラルピンク', hex: '#F19A9A' },
    { name: '선홍색', nameEn: 'Blood Red', nameJa: 'ブラッドレッド', hex: '#911414' },
    { name: '연어색', nameEn: 'Salmon Pink', nameJa: 'サーモンピンク', hex: '#E7A991' },
    { name: '홍옥색', nameEn: 'Ruby Red', nameJa: 'ルビーレッド', hex: '#C51323' },
    { name: '꽃분홍색', nameEn: 'Cherry Pink', nameJa: 'チェリー핑크', hex: '#F07693' },
    { name: '연지색', nameEn: 'Carmine Red', nameJa: 'カーマインレッド', hex: '#5E0000' },
    { name: '형광 분홍색', nameEn: 'Neon Pink', nameJa: 'ネ온핑크', hex: '#FF00E8' },

    // ── 주황 / 갈색 계열 ──────────────────────────────────────────────────────
    { name: '노을색', nameEn: 'Sunset Orange', nameJa: 'サンセットオレンジ', hex: '#B34F18' },
    { name: '황야의 붉은색', nameEn: 'Mesa Red', nameJa: 'メサレッド', hex: '#782D1B' },
    { name: '나무껍질색', nameEn: 'Bark Brown', nameJa: 'バークブラウン', hex: '#301E17' },
    { name: '초콜릿색', nameEn: 'Chocolate Brown', nameJa: 'チョコレートブラウン', hex: '#422C24' },
    { name: '적갈색', nameEn: 'Russet Brown', nameJa: 'ラセットブラウン', hex: '#4D3325' },
    { name: '코볼드색', nameEn: 'Kobold Brown', nameJa: 'コボルドブラウン', hex: '#251B17' },
    { name: '코르크색', nameEn: 'Cork Brown', nameJa: 'コル크ブラウン', hex: '#9D744E' },
    { name: '키키룬색', nameEn: 'Qiqirn Brown', nameJa: 'キキルンブラウン', hex: '#907659' },
    { name: '오포오포색', nameEn: 'Opo-opo Brown', nameJa: 'オポオポブラウン', hex: '#6E5336' },
    { name: '큰뿔염소색', nameEn: 'Aldgoat Brown', nameJa: 'アルドゴートブラウン', hex: '#785F45' },
    { name: '늙은호박색', nameEn: 'Pumpkin Orange', nameJa: 'パンプキンオレンジ', hex: '#C16A1D' },
    { name: '도토리색', nameEn: 'Acorn Brown', nameJa: 'エーコーンブラウン', hex: '#8A643E' },
    { name: '과수원 흙색', nameEn: 'Orchard Brown', nameJa: 'オーチャードブラウン', hex: '#5D4329' },
    { name: '밤색', nameEn: 'Chestnut Brown', nameJa: 'チェ스ナットブラウン', hex: '#3C2718' },
    { name: '고블린색', nameEn: 'Gobbiebag Brown', nameJa: 'ゴブ린ブラウン', hex: '#B9A484' },
    { name: '찰흙색', nameEn: 'Shale Brown', hex: '#918274' },
    { name: '두더지색', nameEn: 'Mole Brown', nameJa: 'モールブラウン', hex: '#51443D' },
    { name: '비옥토색', nameEn: 'Loam Brown', nameJa: 'ロームブラウン', hex: '#342C29' },
    { name: '밝은 주황색', nameEn: 'Bright Orange', nameJa: 'ブライトオレンジ', hex: '#D15616' },

    // ── 흰/노란/크림 계열 ─────────────────────────────────────────────────────
    { name: '상아색', nameEn: 'Bone White', nameJa: 'ボーンホワイト', hex: '#E6D8B6' },
    { name: '울다하 갈색', nameEn: 'Ul Brown', nameJa: 'ウルブラウン', hex: '#B1925F' },
    { name: '사막노란색', nameEn: 'Desert Yellow', nameJa: 'デザートイエロー', hex: '#C39D55' },
    { name: '꿀색', nameEn: 'Honey Yellow', nameJa: 'ハニーイエロー', hex: '#E1B241' },
    { name: '옥수수색', nameEn: 'Millioncorn Yellow', nameJa: 'ミリオンコーンイエロー', hex: '#ECA316' },
    { name: '커얼색', nameEn: 'Coeurl Yellow', nameJa: 'クァールイエロー', hex: '#B98F39' },
    { name: '크림색', nameEn: 'Cream Yellow', nameJa: 'クリームイエロー', hex: '#F1DA9A' },
    { name: '할라탈리 노란색', nameEn: 'Halatali Yellow', hex: '#A18D4D' },
    { name: '건포도색', nameEn: 'Raisin Brown', nameJa: 'レーズンブラウン', hex: '#3A3527' },
    { name: '카나리아색', nameEn: 'Canary Yellow', nameJa: 'カナリーイエロー', hex: '#E9DA67' },
    { name: '바닐라색', nameEn: 'Vanilla Yellow', nameJa: 'バニライエロー', hex: '#E8DEB6' },
    { name: '형광 노란색', nameEn: 'Neon Yellow', nameJa: 'ネオンイエロー', hex: '#ECFF00' },

    // ── 녹색 계열 ─────────────────────────────────────────────────────────────
    { name: '습지 녹색', nameEn: 'Mud Green', nameJa: 'マッドグリーン', hex: '#454731' },
    { name: '실프색', nameEn: 'Sylph Green', nameJa: 'シルフグリーン', hex: '#9E9E66' },
    { name: '라임색', nameEn: 'Lime Green', nameJa: 'ライムグリーン', hex: '#9EAE3E' },
    { name: '이끼색', nameEn: 'Moss Green', nameJa: 'モスグリーン', hex: '#585D36' },
    { name: '풀색', nameEn: 'Meadow Green', nameJa: 'メドウグリーン', hex: '#838A5F' },
    { name: '올리브색', nameEn: 'Olive Green', nameJa: 'オリーブグリーン', hex: '#40412A' },
    { name: '늪지 녹색', nameEn: 'Marsh Green', nameJa: 'マーシュグリーン', hex: '#323528' },
    { name: '풋사과색', nameEn: 'Apple Green', nameJa: 'アップルグリーン', hex: '#97A263' },
    { name: '선인장색', nameEn: 'Cactuar Green', nameJa: 'サ보텐더그린', hex: '#586938' },
    { name: '진녹색', nameEn: 'Hunter Green', nameJa: 'ハンターグリーン', hex: '#283021' },
    { name: '오츄색', nameEn: 'Ochu Green', nameJa: 'オチューグリーン', hex: '#404D31' },
    { name: '금강거북색', nameEn: 'Adamantoise Green', nameJa: 'アダマンタスグリーン', hex: '#313327' },
    { name: '노피카의 녹색', nameEn: 'Nophica Green', nameJa: 'ノフィカグリーン', hex: '#374229' },
    { name: '밀림 녹색', nameEn: 'Deepwood Green', nameJa: '디ープウッドグリーン', hex: '#1E2318' },
    { name: '옅은 청록색', nameEn: 'Turquoise Green', nameJa: 'ターコイズグリーン', hex: '#94B6A6' },
    { name: '터키석색', nameEn: 'Celeste Green', nameJa: 'セレストグリーン', hex: '#2E5952' },
    { name: '몰볼색', nameEn: 'Morbol Green', nameJa: 'モルボルグリーン', hex: '#1F2E2A' },
    { name: '형광 녹색', nameEn: 'Neon Green', nameJa: 'ネオングリーン', hex: '#00FF1B' },

    // ── 하늘 / 파랑 계열 ──────────────────────────────────────────────────────
    { name: '옅은 하늘색', nameEn: 'Ice Blue', nameJa: 'アイスブルー', hex: '#AFBDC2' },
    { name: '하늘색', nameEn: 'Sky Blue', nameJa: 'スカイブルー', hex: '#618090' },
    { name: '바다안개색', nameEn: 'Seafog Blue', nameJa: 'シーフォ그ブルー', hex: '#5D636D' },
    { name: '공잣깃 파란색', nameEn: 'Peacock Blue', nameJa: 'ピーコックブルー', hex: '#38515A' },
    { name: '로타노 바다색', nameEn: 'Rhotano Blue', nameJa: 'ロー타ノブルー', hex: '#1D2D3E' },
    { name: '좀비의 얼굴색', nameEn: 'Corpse Blue', nameJa: 'コープスブルー', hex: '#535A60' },
    { name: '청린수색', nameEn: 'Ceruleum Blue', nameJa: 'セルリウムブルー', hex: '#324451' },
    { name: '쪽빛 파란색', nameEn: 'Woad Blue', nameJa: 'ウォ드ブルー', hex: '#2E364A' },
    { name: '검푸른색', nameEn: 'Ink Blue', nameJa: 'インクブルー', hex: '#1A1C20' },
    { name: '랍토르색', nameEn: 'Raptor Blue', nameJa: 'ラプトルブルー', hex: '#374E79' },
    { name: '오사드 바다색', nameEn: 'Othard Blue', nameJa: 'オサ드ブルー', hex: '#214061' },
    { name: '선명한 파란색', nameEn: 'Storm Blue', nameJa: 'ストームブルー', hex: '#23344D' },
    { name: '보이드의 파란색', nameEn: 'Void Blue', nameJa: 'ヴォイドブルー', hex: '#111A34' },
    { name: '감청색', nameEn: 'Midnight Blue', nameJa: 'ミッドナイトブルー', hex: '#262947' },
    { name: '밤하늘색', nameEn: 'Shadow Blue', nameJa: 'シャドウブルー', hex: '#161826' },
    { name: '청회색', nameEn: 'Abyssal Blue', nameJa: 'アビサルブルー', hex: '#2F3443' },
    { name: '청보라색', nameEn: 'Dragoon Blue', nameJa: 'ドラグーンブルー', hex: '#24243A' },
    { name: '새파란색', nameEn: 'Royal Blue', nameJa: 'ロイヤルブルー', hex: '#172B5E' },
    { name: '담청색', nameEn: 'Turquoise Blue', nameJa: 'ターコイズブルー', hex: '#378297' },
    { name: '짙은 하늘색', nameEn: 'Azure Blue', nameJa: 'アジュアブルー', hex: '#007FFF' },

    // ── 보라 / 연보라 계열 ────────────────────────────────────────────────────
    { name: '라벤더색', nameEn: 'Lavender Purple', nameJa: 'ラベンダーパープル', hex: '#8B80AF' },
    { name: '어두운 보라색', nameEn: 'Gloom Purple', nameJa: 'グルームパープル', hex: '#524661' },
    { name: '머루색', nameEn: 'Currant Purple', nameJa: 'カラン트パープル', hex: '#332D3C' },
    { name: '붓꽃색', nameEn: 'Iris Purple', nameJa: 'アイリスパープル', hex: '#B89FBD' },
    { name: '포도색', nameEn: 'Grape Purple', nameJa: 'グレープパープル', hex: '#3C2B3E' },
    { name: '연꽃색', nameEn: 'Lotus Pink', nameJa: 'ロータス핑크', hex: '#FECFF5' },
    { name: '콜리브리색', nameEn: 'Colibri Pink', nameJa: 'コリブ리핑크', hex: '#DD9CCB' },
    { name: '매화색', nameEn: 'Plum Purple', nameJa: 'プラムパープル', hex: '#7A536D' },
    { name: '자주색', nameEn: 'Regal Purple', hex: '#67314F' },
    { name: '제비꽃색', nameEn: 'Violet Purple', hex: '#6F5AA2' },

    // ── 프리미엄 단색 ─────────────────────────────────────────────────────────
    { name: '순백색', nameEn: 'Pure White', nameJa: 'ピュアホワイト', hex: '#FFFFFF' },
    { name: '칠흑색', nameEn: 'Jet Black', nameJa: 'ジェットブラック', hex: '#1F1F1F' },
    { name: '부드러운 연분홍', nameEn: 'Pastel Pink', nameJa: 'パステル핑크', hex: '#FDC9C7' },
    { name: '짙은 빨강', nameEn: 'Dark Red', nameJa: 'ダークレッド', hex: '#331A1A' },
    { name: '짙은 갈색', nameEn: 'Dark Brown', nameJa: 'ダークブラウン', hex: '#1D1A17' },
    { name: '부드러운 연녹색', nameEn: 'Pastel Green', nameJa: 'パステルグリーン', hex: '#B8D9AB' },
    { name: '짙은 녹색', nameEn: 'Dark Green', nameJa: 'ダークグリーン', hex: '#122312' },
    { name: '부드러운 연파랑', nameEn: 'Pastel Blue', nameJa: 'パステルブルー', hex: '#B1C1D1' },
    { name: '짙은 파랑', nameEn: 'Dark Blue', nameJa: 'ダークブルー', hex: '#0A121A' },
    { name: '부드러운 연보라', nameEn: 'Pastel Purple', nameJa: 'パステルパープル', hex: '#D1B1FF' },
    { name: '짙은 자주색', nameEn: 'Dark Purple', nameJa: 'ダークパープル', hex: '#2A162B' },

    // ── 금속 계열 ─────────────────────────────────────────────────────────────
    { name: '반짝이는 은색', nameEn: 'Metallic Silver', nameJa: 'メタリックシルバー', hex: '#C0C0C0' },
    { name: '반짝이는 금색', nameEn: 'Metallic Gold', nameJa: 'メタリックゴールド', hex: '#D4AF37' },
    { name: '금속질 빨간색', nameEn: 'Metallic Red', nameJa: 'メタリックレッド', hex: '#9C0000' },
    { name: '금속질 주황색', nameEn: 'Metallic Orange', nameJa: 'メタリックオレンジ', hex: '#FF8C00' },
    { name: '금속질 노란색', nameEn: 'Metallic Yellow', nameJa: 'メタリックイエロー', hex: '#FFD700' },
    { name: '금속질 녹색', nameEn: 'Metallic Green', nameJa: 'メタリックグリーン', hex: '#008000' },
    { name: '금속질 하늘색', nameEn: 'Metallic Sky Blue', nameJa: 'メタリックスカイブルー', hex: '#00BFFF' },
    { name: '금속질 파란색', nameEn: 'Metallic Blue', nameJa: 'メタリックブルー', hex: '#0000FF' },
    { name: '금속질 보라색', nameEn: 'Metallic Purple', nameJa: 'メタリックパープル', hex: '#800080' },
    { name: '건메탈색', nameEn: 'Gunmetal Black', nameJa: 'ガンメタル', hex: '#2A2A2A' },
    { name: '진주색', nameEn: 'Pearl White', nameJa: 'パールホワイト', hex: '#FBFCF8' },
    { name: '황동색', nameEn: 'Metallic Brass', nameJa: 'メタリックブラス', hex: '#A17D4D' },
    { name: '금속질 분홍색', nameEn: 'Metallic Pink', nameJa: 'メタリック핑크', hex: '#FF69B4' },
    { name: '금속질 홍옥색', nameEn: 'Metallic Ruby', nameJa: 'メタリックルビー', hex: '#E0115F' },
    { name: '금속질 푸른 녹색', nameEn: 'Metallic Teal', hex: '#0047AB' },
    { name: '금속질 짙은 파랑', nameEn: 'Metallic Dark Blue', nameJa: '메タリックダークブルー', hex: '#00008B' },
];
